name: PR Test & Analysis

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
      - dev

concurrency:
  group: ci-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fetch-and-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: echo Context
        run: |
          echo "${{ github.event.id }}"
          echo "${{ github.event.type }}"
          echo "${{ github.event.actor.id }}"
          echo "${{ github.event.actor.login }}"
          echo "${{ github.event.actor.display_login }}"
          echo "${{ github.event.actor.gravatar_id }}"
          echo "${{ github.event.actor.url }}"
          echo "${{ github.event.actor.avatar_url }}"
          echo "${{ github.event.repo.id }}"
          echo "${{ github.event.repo.name }}"