name: PR Test & Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "dev" ]

concurrency:
  group: ci-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fetch-and-diff:
    runs-on: ci

    outputs:
      modified_modules: ${{ steps.determine_modules.outputs.modules }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set Up Moudles
        run: |
          echo "MODULES=demo demo1" >> $GITHUB_ENV

      - name: Fetch Base Branch
        run: git fetch origin +refs/heads/${{ github.event.pull_request.base.ref}} ||:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Get Modified Files
        run: |
          BASE_SHA=$(git rev-parse origin\${{ github.event.pull_request.base.ref }})
          MODIFIED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} | tr '\n'
          echo "MODIFIED_FIELS=$MODIFIED_FILES" >> $GITHUB_ENV