name: PR Test & Analysis

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
      - dev

concurrency:
  group: ci-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fetch-and-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set Modules
        run: |
          echo "MODULES=demo demo1" >> $GITHUB_ENV

      - name: Fetch Base Branch
        run: git fetch origin +refs/heads/${{ github.ref_name }}:refs/remotes/origin/${{ github.ref_name }}

      - name: Get Modified Files
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.ref_name }})
          echo "${{ github.sha }}"
          echo "$BASE_SHA"
          MODIFIED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} | tr '\n' ' ')
          echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
